config:
  batch_size: 512
  eta: 0.5
  lr: 0.01
  sec_lr: 0.01
dataset_type: tabular
hidden_units:
- 64
- 32
num_features: 447
opt_kwargs:
  initial_accumulator_value: 0.1
optimizer: !!python/name:torch.optim.adagrad.Adagrad ''
