name: fact-ai
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - cudatoolkit=10.2.89
  - numpy=1.19.5
  - pandas=1.2.0
  - python=3.7.5
  - pytorch=1.7.1
  - pytorch-lightning=1.1.3
  - scikit-learn=0.24.0
  - torchvision=0.8.2