adv_cnn_strength: normal
adv_hidden: []
adv_input: !!set
  X: null
  Y: null
config:
  batch_size: 64
  eta: 0.5
  lr: 0.1
dataset_type: tabular
input_shape: 10
num_groups: 4
opt_kwargs:
  initial_accumulator_value: 0.1
optimizer: !!python/name:torch.optim.adagrad.Adagrad ''
pretrain_steps: 250
prim_hidden:
- 64
- 32
