config:
  batch_size: 512
  eta: 0.5
  lr: 0.01
dataset_type: image
hidden_units:
- 64
- 32
num_features: !!python/tuple
- 1
- 28
- 28
opt_kwargs: {}
optimizer: !!python/name:torch.optim.adagrad.Adagrad ''
