adv_hidden: []
adv_input: !!set
  S: null
  X: null
  Y: null
config:
  batch_size: 64
  eta: 0.5
  lr: 0.01
dataset_type: tabular
input_shape: 10
num_groups: 4
opt_kwargs: {}
optimizer: !!python/name:torch.optim.adagrad.Adagrad ''
pretrain_steps: 250
pretrained: false
prim_hidden:
- 64
- 32
