adv_hidden:
- 64
adv_input: !!set
  X: null
  Y: null
config:
  batch_size: 512
  eta: 0.5
  lr: 0.01
dataset_type: image
input_shape: !!python/tuple
- 1
- 28
- 28
num_groups: 2
opt_kwargs: {}
optimizer: !!python/name:torch.optim.adagrad.Adagrad ''
pretrain_steps: 250
pretrained: false
prim_hidden:
- 64
- 32
